import js from "@eslint/js";
import tseslint from "typescript-eslint";
import security from "eslint-plugin-security";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      "dist/**",
      "coverage/**",
      // Generated by scripts/codegen.ts — never hand-edited.
      "src/generated/**",
    ],
  },
  {
    files: ["**/*.ts"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Security plugin only on shipped code, not on tests/scripts.
    // Tests intentionally write fixtures and introspect request bodies;
    // scripts are dev-only tooling. The user-facing surface is src/.
    files: ["src/**/*.ts"],
    plugins: {
      security,
    },
    rules: {
      // security/detect-non-literal-fs-filename: a CLI takes user-provided
      // paths everywhere. Every flagged call already validates the path
      // (output_is_directory, output_exists, assertRegularFile, etc.) or
      // writes to the fixed configDir/stateDir. Enable to catch *new*
      // unvalidated FS calls.
      "security/detect-non-literal-fs-filename": "warn",
      // security/detect-unsafe-regex: the one flagged regex
      // (config.ts icacls parser) is empirically linear and bounded by
      // icacls output. Enable to catch *new* unsafe regexes.
      "security/detect-unsafe-regex": "warn",
      // security/detect-object-injection: every flagged site reads keys
      // from JSON.parse / Object.entries / user-controlled profile names
      // (which safeProfileName now validates). Enable to catch *new*
      // cases where untrusted keys are dereferenced on a plain object.
      "security/detect-object-injection": "warn",
    },
  },
);
