#!/usr/bin/env node
/**
 * Codegen: reads spec/commands.yaml and generates:
 *   - src/generated/command-specs.ts  (immutable command specs)
 *   - docs/commands.md                (generated command reference)
 *
 * Run: pnpm tsx scripts/codegen.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { type CommandSpec, parseCommandsYaml } from "./lib/parse-commands-yaml.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function generateSpecs(commands: CommandSpec[]): string {
  return `// AUTO-GENERATED by scripts/codegen.ts — do not edit by hand
// Based on spec/commands.yaml
export interface CommandSpec {
  name: string;
  summary: string;
  examples: string[];
}

export const commandSpecs: CommandSpec[] = ${JSON.stringify(commands, null, 2)} as const;
`;
}

function toCliCommand(name: string): string {
  return `raindrop ${name.replaceAll(".", " ")}`;
}

function generateDocs(commands: CommandSpec[]): string {
  const lines: string[] = [
    "# Command Reference",
    "",
    "<!-- AUTO-GENERATED by scripts/codegen.ts — do not edit by hand -->",
    "",
    `Generated from spec/commands.yaml on ${new Date().toISOString().split("T")[0]}.`,
    "",
    "Command names below use the actual shell syntax. The source command IDs in `spec/commands.yaml` use dots, for example `bookmark.add` maps to `raindrop bookmark add`.",
    "",
    "## Global flags",
    "",
    "These flags are accepted by the top-level CLI and apply to most commands:",
    "",
    "| Flag | Description |",
    "| ---- | ----------- |",
    "| `--json` | Force JSON output. This is the default stdout contract. |",
    "| `--human` | Print human-readable output where available. |",
    "| `--profile <name>` | Use a named profile for this invocation. |",
    "| `--base-url <url>` | Override the API base URL, mainly for tests and mocks. |",
    "| `--debug` | Include debug details with secret redaction. Do not paste debug output into public issues without reviewing it. |",
    "| `--no-color` | Disable color in human output. |",
    "| `--help` | Show CLI or command help. |",
    "| `--version` | Show the installed version. |",
    "",
    "## Commands",
    "",
    "| Command | Summary |",
    "|---------|---------|",
  ];

  for (const cmd of commands) {
    lines.push(`| \`${toCliCommand(cmd.name)}\` | ${cmd.summary} |`);
  }

  lines.push("");

  for (const cmd of commands) {
    lines.push(`## \`${toCliCommand(cmd.name)}\``, "");
    lines.push(cmd.summary, "");
    if (cmd.examples.length) {
      lines.push("**Examples:**", "");
      lines.push("```bash");
      for (const ex of cmd.examples) lines.push(ex);
      lines.push("```", "");
    }
  }

  return lines.join("\n");
}

// Main
const specPath = join(root, "spec/commands.yaml");
const specText = readFileSync(specPath, "utf8");
const commands = parseCommandsYaml(specText);

const generatedDir = join(root, "src/generated");
mkdirSync(generatedDir, { recursive: true });

const commandSpecsPath = join(generatedDir, "command-specs.ts");
const docsPath = join(root, "docs/commands.md");
const prettierOptions = {
  semi: true,
  trailingComma: "all",
  singleQuote: false,
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  arrowParens: "always",
  endOfLine: "lf",
} as const;

writeFileSync(
  commandSpecsPath,
  await format(generateSpecs(commands), {
    parser: "typescript",
    ...prettierOptions,
  }),
);
writeFileSync(
  docsPath,
  await format(generateDocs(commands), { parser: "markdown", ...prettierOptions }),
);

console.log(`Generated specs for ${commands.length} commands`);
console.log(`  -> src/generated/command-specs.ts`);
console.log(`  -> docs/commands.md`);
